export const SET_ACCESS_TOKEN_INFO = 'SET_ACCESS_TOKEN_INFO';
export const SET_WOW_TOKEN = 'SET_WOW_TOKEN';
export const SET_MYTHIC_PLUS_AFFIXES = 'SET_MYTHIC_PLUS_AFFIXES';
export const API_ERROR = ' API_ERROR';
